### ISSUE TITLE
Client Id for Lenddo API

### ISSUE THREAD

**Issue by AkhileshDahat** [Lenddo/java-lenddo#1]
Hello Team,

I have analyse your api.I have seen this Method
lenddoapi.getClientVerificationAsString("client_id");

I try to integrate the Lenddo  with salesforce.May I know how to get this **client_id** ?

I search for it but nowhere I saw this client_id

**Comment by LenddoTech** [comment]
Hi Akhilesh,

client_id refers to your application id or other unique identifier for this
person or application. Please substitute it there.

Hope this helps. If you need further clarification, we are happy to get on
a call to clarify further.

Best,
Naveen.
On May 27, 2016 5:30 PM, "AkhileshDahat" <notifications@github.com> wrote:

Hello Team,

I have analyse your api.I have seen this Method
lenddoapi.getClientVerificationAsString("client_id");

I try to integrate the Lenddo with salesforce.May I know how to get this
*client_id* ?

I search for it but nowhere I saw this client_id

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lenddo/java-lenddo/issues/1>, or mute the thread
<https://github.com/notifications/unsubscribe/AONJwGxcHKnevLhDjXn_Sfw0MjNrDhDxks5qFtzfgaJpZM4Iob3s>
.

**Comment by Howard3** [comment]
Thank you Naveen.

AkhileshDahat I'll close this ticket for now, if you have further questions please feel free to respond to this thread or reach out to your Lenddo Point of Contact.

Best Regards,
Howard
